--CRIA O BANCO DE DADOS
CREATE DATABASE M_Peoples;
GO

--DEFINE QUAL BANCO DE DADOS SERÁ USADO
USE M_Peoples;
GO

--CRIA AS TABELAS DO BANCO DE DADOS
CREATE TABLE Funcionarios (
	IdFuncionario  INT PRIMARY KEY IDENTITY,
	Nome		   VARCHAR (255) NOT NULL,
	Sobrenome	   VARCHAR (255) NOT NULL,
);
GO

-- Adiciona a coluna DataNascimento na tabela Funcionarios
ALTER TABLE Funcionarios
ADD DataNascimento DATE

--CRIAR TABELA TIPOUSUARIO
CREATE TABLE TipoUsuario (
	IdTipoUsuario INT PRIMARY KEY IDENTITY,
	Titulo		  VARCHAR (255) NOT NULL,
);
GO

--CRIA TABELA USUARIO
CREATE TABLE Usuario (
	IdUsuario INT PRIMARY KEY IDENTITY,
	Email	  VARCHAR (255) NOT NULL UNIQUE,
	Senha	  VARCHAR (255) NOT NULL,

	IdTipoUsuario INT FOREIGN KEY REFERENCES TipoUsuario (IdTipoUsuario),
);
GO

--ADICIONA A COLUNA ID USUARIO NA TABELA FUNCIONARIOS
ALTER TABLE Funcionarios
ADD IdUsuario INT
